name: mini-otel-lgtm

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      # MINIO_DOMAIN: domain
    command: server /data --console-address :9001
    volumes:
      - ./minio-data:/data

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./alloy-config.river:/etc/alloy/config.alloy
    ports:
      - 4317:4317
      - 12345:12345
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    command:
      - --config.file=/etc/loki/local-config.yaml

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    volumes:
      - ./mimir-config.yaml:/etc/mimir/config.yaml
    ports:
      - 9009:9009
    command:
      - --config.file=/etc/mimir/config.yaml
      - --config.expand-env=true
      - --target=all

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./tempo-config.yaml:/etc/tempo/config.yaml
    command:
      - --config.file=/etc/tempo/config.yaml
    ports:
      - 3200:3200 # tempo http
      # - 9095:9095 # tempo grpc
      # - 4317:4317 # otlp grpc
      # - 4318:4318 # otlp http

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/default.yaml
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    ports:
      - 3000:3000
