auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  # grpc_listen_port: 9096

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2000-01-01
    store: tsdb
    object_store: filesystem
    schema: v12
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
